### ISSUE TITLE
Providing resources separated by brain region to overcome the high memory necessary to open the huge file

### ISSUE THREAD

**Issue by MariaRosariaNucera** [linnarsson-lab/developing-human-brain#10]
Hello,
First of all, thank you, this resource is really great and super useful.
Unfortunately, opening this file is very challenging without the access to high computational resources.

This atlas is very big and contains a lot of brain regions, I think that most people would like to use it to reference mapping their dataset or compare it with their in-vitro data. For this reason, probably the only need a specific brain region, eg only the Telencephalon or only the Midbrain. 

I would like to subset the dataset and get just the Telencephalon, but I need to be able to open the big dataset first and convert it to an Anndata...but it always runs out of RAM.

It would be great if you could also consider uploading the altas separated for brain regions, so people could just downloaded the region of interest and it would be really easier to menage due to the reduced number of cells.

Thank you!
Maria

**Comment by ghost** [comment]
I also think this would be a good idea to quickly access a smaller h5ad file for initial tests, then probably move to shoji or the larger h5ad file provided now
