### ISSUE TITLE
How to read HumanFetalBrainPool.h5 into Seurat

### ISSUE THREAD

**Issue by vertesy** [linnarsson-lab/developing-human-brain#12]
Hey, 

thank you for sharing this great resource.  I am not familiar with the h5 and format nor the cytograph-shoji pipeline.

I would like to read `HumanFetalBrainPool.h5` (or the other provided fully processed files with meta data) into Seurat. similar to as described [here](https://www.reddit.com/r/bioinformatics/comments/146b1ev/trouble_converting_h5_file_to_seurat_object/?rdt=57794).

I tried multiple suggestions found on the web or in #2, but did not manage to get a Seurat object. I stumbled on too many suggestions: sceasy, schard, rhdf5, HDF5Array, SeuratDisk, Seurat's Read10X_h5, with most of the suggestions just saying "use this". However, it seems specific details are crucial.

Most approaches failed with an error about "X not found in the h5 file", I assume because h5 is a generic format, and the loader should know exactly what and how is stored inside. 

If someone could help out which exact packages and it would be great! Thank you!

**Comment by yojetsharma** [comment]
```
install.packages("BiocManager")
BiocManager::install("rhdf5")
h5_file <- H5Fopen("HumanFetalBrainPool.h5", flags = "H5F_ACC_RDONLY")
#Check all the things that are there in the file by running
h5_file$CellClass #(CellClass, for example, is the metadata for annotation)
h5ls("HumanFetalBrainPool.h5") 
metadata <- h5read(h5_file, "shoji/CellClass")
counts<-h5read(h5_file, "shoji/Expression)
seurat_obj<-CreateSeuratObject(counts, metadata)
h5close(h5_file)
```

**Comment by vertesy** [comment]
Thank you very much!
