### ISSUE TITLE
Developing human brain color_dictionary

### ISSUE THREAD

**Issue by rodrisenovilla** [linnarsson-lab/developing-human-brain#4]
First of all, thank you for this incredible data and resources. Exploring this human data is really exciting! 

I am trying to make use of your Spatial EEL FISH datasets. To do so, I have followed FISHscale multi-dataset tutorial (https://github.com/linnarsson-lab/FISHscale/blob/master/example_notebooks/FISHscale_tutorial_multi_dataset.ipynb). Although it is really straightforward and easy to follow, it is based on Mouse atlas and the given data (https://figshare.com/articles/dataset/EEL_mouse_sagittal_atlas_RNA_168_genes_spatial_data/20324814), as the color_dictionary, don't match developing human samples color_dictionary. 

I am wondering whether you may have a similar FigShare repository that I have not been able to find, if you could upload developing_human_color_dictionary in this github branch or any other instruction to reproduce the analysis. 

Thank you very much in advance, really looking forward to explore the spatial data!
Best wishes,
Rodrigo Senovilla Ganzo

**Comment by larsborm** [comment]
Hi Rodrigo, 
Sorry for the late reply, I missed this issue.

It is not mandatory to provide a color dictionary to FISHscale. If you provide `None` it will generate a new random color dictionary. This is then stored under `d.color_dict`, which you can also modify. 

For the figures we used a custom color set based on the Spectral color palette from [farrow-and-ball](https://pypi.org/project/farrow-and-ball/). The actual colors are listed below.

```python
genes = ['OLIG3', 'STMN2' ,'PAX6', 'SHH', 'NKX2-2', 'EMX2', 'EN2', 'WNT2B',  'FOXG1', 'NKX2-1', 'FGF17', 'WNT1',  'SIX6',  'BARHL1', 'FGF8' ]

colors = np.array([[0.65997693, 0.24341407, 0.29845444, 1.        ],
       [0.29379469, 0.57416378, 0.41305652, 1.        ],
       [0.85748558, 0.455594  , 0.27077278, 1.        ],
       [0.74717416, 0.29822376, 0.38066897, 1.        ],
       [17/256, 142/256, 214/256, 1.        ],
       [0.33605536, 0.5055594 , 0.59953864, 1.        ],
       [0.71174164, 0.7249827 , 0.416609  , 1.        ],
       [0.44576701, 0.66136101, 0.44046136, 1.        ],
       [0.7578316 , 0.31441753, 0.25914648, 1.        ],
       [0.35898501, 0.54985006, 0.68143022, 1.        ],
       [0.24978085, 0.52350634, 0.45042676, 1.        ],
       [230/256, 193/256  , 32/256, 1.        ], 
       [0.91229527, 0.70472895, 0.36544406, 1.        ],
       [224/256, 89/256, 139/256],
        [0.34901961, 0.61960784, 0.76862745, 1.        ],
        ])

fig, ax = plt.subplots(figsize=(10,10))

for g, c in zip(genes, colors):
    xy = d640.get_gene(g).to_numpy() #d640 is the FISHscale dataset with a Z level of 640um.
    ax.scatter(xy[:,0], xy[:,1], color=c, s=1.3, label=g)
    
ax.set_aspect('equal')
ax.set_axis_off()
ax.invert_xaxis()
```

**Comment by rodrisenovilla** [comment]
Hi Lars,
Thank you for the reply!
I was following a tutorial that included the color_dict, and I thought it was needed.
I have successfully accessed to your resource, thank you very much and great work!
Best,
Rodrigo
